BlogProject/urls.py
from django import views
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from blog.upload import upload_image

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    # url(r"^uploads/(?P<path>.*)$", "django.views.static.serve", {"document_root": settings.MEDIA_ROOT,}),
    path('admin/upload/', upload_image, name='upload_image'),
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('archives/', views.archives, name='archives'),
    path('article_detail/', views.article_detail, name='article_detail'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
    path('category/', views.category, name='category'),
    path('comment/post/', views.comment_post, name='comment_post'),
]

blog/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

# 用户模型.
# 第一种：采用的继承方式扩展用户信息（本系统采用）
# 扩展：关联的方式去扩展用户信息
class User(AbstractUser):
    avatar = models.ImageField(upload_to='avatar/%Y/%m', default='avatar/default.png', max_length=200, blank=True, null=True, verbose_name='用户头像')
    qq = models.CharField(max_length=20, blank=True, null=True, verbose_name='QQ号码')
    mobile = models.CharField(max_length=11, blank=True, null=True, unique=True, verbose_name='手机号码')
    url = models.URLField(max_length=100, blank=True, null=True, verbose_name='个人网页地址')

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __unicode__(self):
        return self.username


# 标签
class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='标签名称')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


# 分类
class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name='分类名称')
    index = models.IntegerField(default=999, verbose_name='分类的排序')

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


# 自定义一个文章Model的管理器
# 1、新加一个数据处理的方法
# 2、改变原有的queryset
class ArticleManager(models.Manager):
    def distinct_date(self):
        distinct_date_list = []
        date_list = self.values('date_publish')
        for date in date_list:
            date = date['date_publish'].strftime('%Y/%m文章存档')
            if date not in distinct_date_list:
                distinct_date_list.append(date)
        return distinct_date_list


# 文章模型
class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=50, verbose_name='文章描述')
    content = models.TextField(verbose_name='文章内容')
    click_count = models.IntegerField(default=0, verbose_name='点击次数')
    is_recommend = models.BooleanField(default=False, verbose_name='是否推荐')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, blank=True, null=True, verbose_name='分类', on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, verbose_name='标签')

    objects = ArticleManager()

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']

    def __unicode__(self):
        return self.title


# 评论模型
class Comment(models.Model):
    content = models.TextField(verbose_name='评论内容')
    username = models.CharField(max_length=30, blank=True, null=True, verbose_name='用户名')
    email = models.EmailField(max_length=50, blank=True, null=True, verbose_name='邮箱地址')
    url = models.URLField(max_length=100, blank=True, null=True, verbose_name='个人网页地址')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    user = models.ForeignKey(User, blank=True, null=True, verbose_name='用户', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, blank=True, null=True, verbose_name='文章', on_delete=models.CASCADE)
    pid = models.ForeignKey('self', blank=True, null=True, verbose_name='父级评论', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return str(self.id)


# 友情链接
class Links(models.Model):
    title = models.CharField(max_length=50, verbose_name='标题')
    description = models.CharField(max_length=200, verbose_name='友情链接描述')
    callback_url = models.URLField(verbose_name='url地址')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    index = models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        ordering = ['index', 'id']

    def __unicode__(self):
        return self.title


# 广告
class Ad(models.Model):
    title = models.CharField(max_length=50, verbose_name='广告标题')
    description = models.CharField(max_length=200, verbose_name='广告描述')
    image_url = models.ImageField(upload_to='ad/%Y/%m', verbose_name='图片路径')
    callback_url = models.URLField(null=True, blank=True, verbose_name='回调url')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    index = models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')

    class Meta:
        verbose_name = u'广告'
        verbose_name_plural = verbose_name
        ordering = ['index', 'id']

    def __unicode__(self):
        return self.title

blog/forms.py
# -*- coding:utf-8 -*-
from django import forms


class LoginForm(forms.Form):
    """
    登录Form
    """
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username", "required": "required", }),
                               max_length=50, error_messages={"required": "username不能为空", })
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password", "required": "required", }),
                               max_length=20, error_messages={"required": "password不能为空", })


class RegForm(forms.Form):
    """
    注册表单
    """
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username", "required": "required", }),
                               max_length=50, error_messages={"required": "username不能为空", })
    email = forms.EmailField(widget=forms.TextInput(attrs={"placeholder": "Email", "required": "required", }),
                             max_length=50, error_messages={"required": "email不能为空", })
    url = forms.URLField(widget=forms.TextInput(attrs={"placeholder": "Url", }),
                         max_length=100, required=False)
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password", "required": "required", }),
                               max_length=20, error_messages={"required": "password不能为空", })


class CommentForm(forms.Form):
    """
    评论表单
    """
    author = forms.CharField(widget=forms.TextInput(attrs={"id": "author", "class": "comment_input", "required": "required", "size": "25", "tabindex": "1"}),
                             max_length=50, error_messages={"required": "username不能为空", })
    email = forms.EmailField(widget=forms.TextInput(attrs={"id": "email", "type": "email", "class": "comment_input", "required": "required", "size": "25", "tabindex": "2"}),
                             max_length=50, error_messages={"required": "email不能为空", })
    url = forms.URLField(widget=forms.TextInput(attrs={"id": "url", "type": "url", "class": "comment_input", "size": "25", "tabindex": "3"}),
                         max_length=100, required=False)
    comment = forms.CharField(widget=forms.Textarea(attrs={"id": "comment", "class": "message_input", "required": "required", "cols": "25", "rows": "5", "tabindex": "4"}),
                              error_messages={"required": "评论不能为空", })
    article = forms.CharField(widget=forms.HiddenInput())

blog/views.py
# -*- coding: utf-8 -*-
import logging

from django.conf import settings
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.hashers import make_password
from django.core.paginator import *
from django.db.models import Count
from django.shortcuts import render, redirect

from blog.forms import *
from blog.models import *

logger = logging.getLogger("blog.views")


# Create your views here.

def global_setting(request):
    # 站点基本信息
    SITE_URL = settings.SITE_URL
    SITE_NAME = settings.SITE_NAME
    SITE_DESC = settings.SITE_DESC

    # 导航栏类别信息获取
    category_list = Category.objects.all()
    # 文章归档
    archive_list = Article.objects.distinct_date()
    # 评论排行
    comment_count_list = Comment.objects.values('article').annotate(comment_count=Count('article')).order_by('-comment_count')
    article_comment_list = [Article.objects.get(pk=comment['article']) for comment in comment_count_list]

    return locals()


# 首页
def index(request):
    # 最新文章数据获取
    article_list = Article.objects.all()
    article_list = get_page(request, article_list)

    return render(request, "blog/index.html", locals())  # 使用locals()将当前函数的所有局部变量传递到页面中
    # return render(request, "blog/index.html", {'category_list': category_list, 'article_list': article_list})


# 文章归档
def archives(request):
    try:
        year = request.GET.get('year', None)
        month = request.GET.get('month', None)
        article_list = Article.objects.filter(date_publish__icontaines=year + '-' + month)
        article_list = get_page(request, article_list)
    except Exception as result:
        print(result)
    return render(request, 'blog/archive.html', locals())


# 分页
def get_page(request, article_list):
    paginator = Paginator(article_list, 10)
    try:
        page = int(request.GET.get('page', 1))
        article_list = paginator.page(page)
    except (EmptyPage, InvalidPage, PageNotAnInteger):
        article_list = paginator.page(1)
    return article_list


# 文章详情
def article_detail(request):
    try:
        # 获取文章id
        article_id = request.GET.get('id', None)
        try:
            # 获取文章信息
            article = Article.objects.get(pk=article_id)
        except Article.DoesNotExist:
            return render(request, 'blog/failure.html', {'reason': '没有找到对应的文章'})

        # 评论表单
        comment_form = CommentForm({'author': request.user.username,
                                    'email': request.user.email,
                                    'url': request.user.url,
                                    'article': article_id} if request.user.is_authenticated() else {'article': article_id})
        comments = Comment.objects.filter(article=article).order_by('id')
        comment_list = []
        for comment in comments:
            for item in comment_list:
                if not hasattr(item, 'children_comment'):
                    setattr(item, 'children_comment', [])
                if comment.pid == item:
                    item.children_comment.append(comment)
                    break
            if comment.pid is None:
                comment_list.append(comment)
    except Exception as result:
        print(result)
    return render(request, 'blog/article_detail.html', locals())


# 提交评论
def comment_post(request):
    try:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # 获取表单信息
            comment = Comment.objects.create(username=comment_form.cleaned_data["author"],
                                             email=comment_form.cleaned_data["email"],
                                             url=comment_form.cleaned_data["url"],
                                             content=comment_form.cleaned_data["comment"],
                                             article_id=comment_form.cleaned_data["article"],
                                             user=request.user if request.user.is_authenticated() else None)
            comment.save()
        else:
            return render(request, 'blog/failure.html', {'reason': comment_form.errors})
    except Exception as e:
        logger.error(e)
    return redirect(request.META['HTTP_REFERER'])


# 注册
def register(request):
    try:
        if request.method == 'POST':
            reg_form = RegForm(request.POST)
            if reg_form.is_valid():
                # 注册
                user = User.objects.create(username=reg_form.cleaned_data["username"],
                                           email=reg_form.cleaned_data["email"],
                                           url=reg_form.cleaned_data["url"],
                                           password=make_password(reg_form.cleaned_data["password"]), )
                user.save()

                # 登录
                user.backend = 'django.contrib.auth.backends.ModelBackend'  # 指定默认的登录验证方式
                login(request, user)
                return redirect(request.POST.get('source_url'))
            else:
                return render(request, 'blog/failure.html', {'reason': reg_form.errors})
        else:
            reg_form = RegForm()
    except Exception as e:
        logger.error(e)
    return render(request, 'blog/register.html', locals())


# 登录
def login(request):
    try:
        if request.method == 'POST':
            login_form = LoginForm(request.POST)
            if login_form.is_valid():
                # 登录
                username = login_form.cleaned_data["username"]
                password = login_form.cleaned_data["password"]
                user = authenticate(username=username, password=password)
                if user is not None:
                    user.backend = 'django.contrib.auth.backends.ModelBackend'  # 指定默认的登录验证方式
                    login(request, user)
                else:
                    return render(request, 'blog/failure.html', {'reason': '登录验证失败'})
                return redirect(request.POST.get('source_url'))
            else:
                return render(request, 'blog/failure.html', {'reason': login_form.errors})
        else:
            login_form = LoginForm()
    except Exception as e:
        logger.error(e)
    return render(request, 'blog/login.html', locals())


# 注销
def logout(request):
    try:
        logout(request)
    except Exception as e:
        print(e)
        logger.error(e)
    return redirect(request.META['HTTP_REFERER'])


def category(request):
    try:
        # 先获取客户端提交的信息
        cid = request.GET.get('cid', None)
        try:
            category = Category.objects.get(pk=cid)
        except Category.DoesNotExist:
            return render(request, 'blog/failure.html', {'reason': '分类不存在'})
        article_list = Article.objects.filter(category=category)
        article_list = get_page(request, article_list)
    except Exception as e:
        logger.error(e)
    return render(request, 'blog/category.html', locals())

blog/templates/blog/archive.html
{% extends 'blog/base.html' %}
{% load static %}

{% block left_content %}
    {% include 'blog/ad.html' %}
    <div class="topnews">
        <h2>{{ request.GET.year }}/{{ request.GET.month }}文章归档</h2>
        {% for article in archive_list %}
            <div class="blogs">
                <ul>
                    <h3><a href="/">{{ article.title }}</a></h3>
                    <p>{{ article.desc }}</p>
                    <p class="autor">
                        <span class="lm f_l">
                            {% for tag in article.tag.all %}
                                <a href="/">{{ tag.name }}</a>
                            {% endfor %}
                        </span>
                        <span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span>
                        <span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span>
                        <span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span>
                    </p>
                </ul>
            </div>
        {% endfor %}
    </div>
    {% include 'blog/pagination.html' %}
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load my_filter %}
{% block left_content %}
    <div class="postdate">
        <div class="month">{{ article.date_publish | month_to_upper }}</div>
        <div class="date">{{ article.date_publish | date:'d' }}</div>
    </div>
    <div class="title">
        <h2>
            <a href="" rel="bookmark" title="{{ article.title }}">{{ article.title }}</a>
        </h2>
        <div class="postmeta">
            <span class="postmeta_author">{{ article.user.username }}</span>
            <span class="postmeta_category"><a href="" rel="category">{{ article.category.name }}</a></span>
            <span class="postmeta_time">{{ article.date_publish | date:'Y-m-d' }}</span>
        </div>
    </div>
    <div class="entry">
        {{ article.content | safe }}
    </div>
    <span class="tags">
    {% for tag in article.tag.all %}
        <a href="?tag={{ tag.name }}" rel="tag">{{ tag.name }}</a>
    {% endfor %}
    </span>
    <div class="info">
        Address:
        <a href="{{ SITE_URL }}article_detail/?id={{ article.id }}" rel="bookmark" title="{{ article.title }}">{{ SITE_URL }}article/?id={{ article.id }}</a>
    </div>
    <div class="commentstitle">
        <h3 id="comments">
            <span class="commentsnumber">only {{ article.comment_set.all.count }} comment</span>
            untill now
        </h3>
    </div>
    <ol class="commentlist">
        {% for comment in comment_list %}
            <li id="comment-59418">
                <div class="top">
                    <a href='{{ comment.url }}' rel='external nofollow' class='url'>{{ comment.username }}</a>
                    <span class="time"> @ <a href="#comment-59418" title="">{{ comment.date_publish | date:'Y-m-d H:i:s' }}</a></span>
                </div>
                <div>
                    <img alt='' src='{% static 'blog/images/default.jpg' %}' class='avatar avatar-32 photo' height='32' width='32'/>
                </div>
                <div class="body">
                    <p>{{ comment.content }}</p>
                </div>
            </li>
            {% for children_comment in comment.children_comment %}
                <li id="comment-59542">
                    <div class="reply">
                        <div class="top">
                            <a href="{{ children_comment.url }}" rel="external nofollow" class="url">{{ children_comment.username }}</a>
                            <span class="time"> @ <a href="#comment-59543" title="">{{ children_comment.date_publish | date:'Y-m-d H:i:s' }}</a></span>
                        </div>
                        <div>
                            <img alt="" src="{% static 'blog/images/default.jpg' %}" class="avatar avatar-32 photo" height="32" width="32">
                        </div>
                        <div class="body">
                            {{ children_comment.content }} </div>
                    </div>
                </li>
            {% endfor %}
        {% endfor %}
    </ol>
    <div id="commentform">
        <h3 id="respond">Add your comment now</h3>
        {% if not request.user.is_authenticated %}
            <div class='login_info'>还没有登陆？可以登录后再评论哦。
                <b>
                    <a href="{% url 'blog:login' %}">&raquo;去登录</a>&nbsp;<a href="{% url 'blog:register' %}">&raquo;去注册</a>
                </b>
            </div>
        {% else %}
            <div class='login_info'>
                <b>{{ request.user.username }}</b>
                ,快来写点评论吧!&nbsp;<a href="{% url 'blog:logout' %}">注销</a>
            </div>
        {% endif %}
        <form action="{% url 'blog:comment_post' %}" method="post">
            {% csrf_token %}
            <p>{{ comment_form.author }}
                <label for="author">Name (required)</label>
            </p>
            <p>{{ comment_form.email }}
                <label for="email">Email (Will NOT be published) (required)</label>
            </p>
            <p>{{ comment_form.url }}
                <label for="url">URL</label>
            </p>
            <p>{{ comment_form.comment }}</p>
            <p>
                {{ comment_form.article }}
                <input name="submit" type="submit" id="submit" tabindex="5" value="Submit" class="button"/>
            </p>
        </form>
    </div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ SITE_NAME }}</title>
    <meta name="keywords" content="{{ SITE_NAME }}"/>
    <meta name="description" content="{{ SITE_DESC }}"/>
    <link href="{% static 'blog/css/base.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/index.css' %}" rel="stylesheet">
    {% block custom_css %} {% endblock %}
    <script type="text/javascript" src="{% static 'blog/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'blog/js/sliders.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.js' %}"></script>
    {% block custom_js %} {% endblock %}
</head>
<body>
<header>
    <div class="logo">
        <h1>{{ SITE_NAME }}</h1>
        <p>{{ SITE_DESC }}</p>
    </div>
    <nav id="topnav" class="f_r">
        <ul>
            {% for category in category_list %}
                <a href="base.html" target="_blank">{{ category.name }}</a>
            {% endfor %}
        </ul>
        <script src="{% static 'blog/js/nav.js' %}"></script>
    </nav>
</header>
<article>
    <div class="l_box f_l">
        {% block left_content %} {% endblock %}
    </div>
    <div class="r_box f_r">
        <div class="tit01">
            <h3>关注我</h3>
            <div class="gzwm">
                <ul>
                    <li><a class="xlwb" href="#" target="_blank">新浪微博</a></li>
                    <li><a class="txwb" href="#" target="_blank">腾讯微博</a></li>
                    <li><a class="rss" href="portal.php?mod=rss" target="_blank">RSS</a></li>
                    <li><a class="wx" href="mailto:admin@admin.com">邮箱</a></li>
                </ul>
            </div>
        </div>
        <!--tit01 end-->
        <div class="moreSelect" id="lp_right_select">
            <script>
                window.onload = function () {
                    var oLi = document.getElementById("tab").getElementsByTagName("li");
                    var oUl = document.getElementById("ms-main").getElementsByTagName("div");

                    for (var i = 0; i < oLi.length; i++) {
                        oLi[i].index = i;
                        oLi[i].onmouseover = function () {
                            for (var n = 0; n < oLi.length; n++) oLi[n].className = "";
                            this.className = "cur";
                            for (var n = 0; n < oUl.length; n++) oUl[n].style.display = "none";
                            oUl[this.index].style.display = "block"
                        }
                    }
                }
            </script>
            <div class="ms-top">
                <ul class="hd" id="tab">
                    <li class="cur"><a href="/">浏览排行</a></li>
                    <li><a href="/">评论排行</a></li>
                    <li><a href="/">站长推荐</a></li>
                </ul>
            </div>
            <div class="ms-main" id="ms-main">
                <div style="display: block;" class="bd bd-news">
                    <ul>
                        <li><a href="/" target="_blank">住在手机里的朋友</a></li>
                        <li><a href="/" target="_blank">教你怎样用欠费手机拨打电话</a></li>
                        <li><a href="/" target="_blank">原来以为，一个人的勇敢是，删掉他的手机号码...</a></li>
                        <li><a href="/" target="_blank">手机的16个惊人小秘密，据说99.999%的人都不知</a></li>
                        <li><a href="/" target="_blank">你面对的是生活而不是手机</a></li>
                        <li><a href="/" target="_blank">豪雅手机正式发布! 在法国全手工打造的奢侈品</a></li>
                    </ul>
                </div>
                <div class="bd bd-news">
                    <ul>
                        {% for comment in article_comment_list %}
                            <li><a href="/" target="_blank">{{ comment.title | slice:':15' }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="bd bd-news">
                    <ul>
                        <li><a href="/" target="_blank">原来以为，一个人的勇敢是，删掉他的手机号码...</a></li>
                        <li><a href="/" target="_blank">手机的16个惊人小秘密，据说99.999%的人都不知</a></li>
                        <li><a href="/" target="_blank">住在手机里的朋友</a></li>
                        <li><a href="/" target="_blank">教你怎样用欠费手机拨打电话</a></li>
                        <li><a href="/" target="_blank">你面对的是生活而不是手机</a></li>
                        <li><a href="/" target="_blank">豪雅手机正式发布! 在法国全手工打造的奢侈品</a></li>
                    </ul>
                </div>
            </div>
            <!--ms-main end -->
        </div>
        <!--切换卡 moreSelect end -->

        <div class="cloud">
            <h3>标签云</h3>
            <ul>
                <li><a href="/">个人博客</a></li>
                <li><a href="/">web开发</a></li>
                <li><a href="/">前端设计</a></li>
                <li><a href="/">Html</a></li>
                <li><a href="/">CSS3</a></li>
                <li><a href="/">Html5+css3</a></li>
                <li><a href="/">百度</a></li>
                <li><a href="/">Javasript</a></li>
                <li><a href="/">web开发</a></li>
                <li><a href="/">前端设计</a></li>
                <li><a href="/">Html</a></li>
                <li><a href="/">CSS3</a></li>
                <li><a href="/">Html5+css3</a></li>
                <li><a href="/">百度</a></li>
            </ul>
        </div>
        <div class="tuwen">
            <h3>文章归档</h3>
            <ul>
                {% for archive in archive_list %}
                    <li>
                        <p><span class="tutime font-size-18"><a href='{% url 'blog:archives' %}?year={{ archive | slice:":4" }}&month={{ archive | slice:"5:7" }}'>{{ archive }}</a></span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="links">
            <h3>友情链接</h3>
            <ul>
                <li><a href="/">web开发</a></li>
                <li><a href="/">前端设计</a></li>
                <li><a href="/">Html</a></li>
                <li><a href="/">CSS3</a></li>
                <li><a href="/">Html5+css3</a></li>
                <li><a href="/">百度</a></li>
            </ul>
        </div>
    </div>
    <!--r_box end -->
</article>
<footer>
    <p class="ft-copyright">某某某的个人博客 蜀ICP备xxxxxxx号-1</p>
    <div id="tbox"><a id="togbook" href="/"></a> <a id="gotop" href="javascript:void(0)"></a></div>
</footer>
</body>
</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% load static %}
{% block left_content %}
    {% include 'blog/ad.html' %}
    <div class="topnews">
        <h2>{{ category.name }}</h2>
        {% for article in article_list %}
            <div class="blogs">
                <ul>
                    <h3>
                        <a href="/">{{ article.title }}</a>
                    </h3>
                    <p>{{ article.desc }}</p>
                    <p class="autor">
                        <span class="lm f_l">{% for tag in article.tag.all %}
                            <a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}
                        <span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span>
                        <span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span>
                        <span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span>
                    </p>
                </ul>
            </div>
        {% endfor %}
    </div>
    {% include 'blog/pagination.html' %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}

{% block left_content %}
    {% include 'blog/ad.html' %}
    <div class="topnews">
        <h2>最新文章</h2>
        {% for article in article_list %}
            <div class="blogs">
                <ul>
                    <h3>
                        <a href="{% url 'blog:article_detail' %}?id={{ article.id }}">{{ article.title }}</a>
                    </h3>
                    <p>{{ article.desc }}</p>
                    <p class="autor">
                        <span class="lm f_l">
                            {% for tag in article.tag.all %}
                                <a href="/">{{ tag.name }}</a>
                            {% endfor %}
                        </span>
                        <span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span>
                        <span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span>
                        <span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span>
                    </p>
                </ul>
            </div>
        {% endfor %}
    </div>
    {% include 'blog/pagination.html' %}
{% endblock %}

blog/templates/blog/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link href="{% static 'blog/css/reglogin.css' %}" rel='stylesheet' type='text/css'/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="main">
    <div class="header">
        <h1>Create a Free Account!</h1>
    </div>
    <p></p>
    <form action="{% url 'blog:register' %}" method="post">
        {% csrf_token %}
        <ul class="left-form">
            <h2>New Account:</h2>
            <li>
                {{ reg_form.username }}
                <div class="clear"></div>
            </li>
            <li>
                {{ reg_form.email }}
                <div class="clear"></div>
            </li>
            <li>
                {{ reg_form.url }}
                <div class="clear"></div>
            </li>
            <li>
                {{ reg_form.password }}
                <div class="clear"></div>
            </li>
            <input type="hidden" name="source_url" value="{{ request.META.HTTP_REFERER }}">
            <input type="submit" value="Create And Login">
            <div class="clear"></div>
        </ul>
        <div class="clear"></div>
    </form>
</div>
</body>
</html>

blog/templates/blog/success.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>操作成功</title>
    <link href="http://www.maiziedu.com/static/css/base.css" rel="stylesheet">
    <link href="http://www.maiziedu.com/static/css/microoh-v5.css" rel="stylesheet">
</head>

<body>
<div class="microoh-main" style="height: 100px">
    <div style="position: absolute; top: 20px; left: 20px;">
        <i class="v5-icon v5-icon-right"></i>
        <span>{{ reason | safe }}</span>
    </div>
</div>
</body>
</html>